# Docker Dev
version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /home/shobhit/repos/github.com/sharmashobhit/sharmashobh.it/src/content:/docs
    ports:
      - 8001:8000
    command: ["python", "simgen_ssg/__main__.py", "serve", "--dir", "/docs/", "--bind", "0.0.0.0:8000", "--watch"]
